auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: nilsun.github.io
url: http://nilsun.github.io/
feed: /atom.xml
author_info: <a href="http://nilsun.github.io/">Nilsun</a>